# Generated by Django 4.2.2 on 2023-07-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='img',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
    ]
