# Generated by Django 4.2.3 on 2023-07-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogcontent_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='author',
        ),
    ]
